In [6]:
import random
import pandas as pd
from faker import Faker
from datetime import datetime, timedelta

# Initialize Faker for generating Indian names
fake = Faker("en_IN")

# List of sample airlines, cities, and classes
airlines = [
    "Air India", "IndiGo", "SpiceJet", "Go First", "Vistara", "AirAsia India", 
    "Alliance Air", "Star Air", "TruJet", "Akasa Air"
]
cities = [
    "Delhi", "Mumbai", "Chennai", "Kolkata", "Bangalore", "Hyderabad", 
    "Ahmedabad", "Pune", "Jaipur", "Lucknow", "Cochin", "Goa", "Patna", "Indore"
]
classes = ["Economy", "Business", "Premium Economy"]

# Generate random data
passenger_data = []
flight_booking_data = []

# Create data for passengers and flight bookings
for passenger_id in range(1, 201):  # Generate 200 passengers (each passenger can have multiple bookings)
    passenger_name = fake.name()  # Generate a fake Indian name
    travel_class = random.choice(classes)
    
    passenger_data.append({
        "Passenger_ID": passenger_id,
        "Passenger_Name": passenger_name,
        "Class": travel_class
    })
    
    # For each passenger, generate random flight bookings
    num_bookings = random.randint(1, 3)  # Each passenger can have 1 to 3 bookings
    
    for _ in range(num_bookings):
        airline = random.choice(airlines)
        source, destination = random.sample(cities, 2)  # Ensure source != destination

        # Generate booking date
        booking_date = datetime(2018, 1, 1) + timedelta(days=random.randint(0, 1825))  # Random date between 2018 and 2023

        # Generate travel date and time (departure)
        travel_date = booking_date + timedelta(days=random.randint(1, 30))  # Travel date after booking date
        departure_time = travel_date + timedelta(hours=random.randint(5, 21), minutes=random.randint(0, 59))  # Departure time

        # Generate arrival date and time
        duration = timedelta(hours=random.randint(1, 7), minutes=random.randint(0, 59))  # Max duration of 7-8 hours
        arrival_time = departure_time + duration  # Arrival time is after departure

        # Introduce "dirty data" by modifying these columns:
        # Randomly introduce null values in booking or travel dates, airline names, or price
        if random.random() < 0.1:  # 10% chance of null value in booking date
            booking_date = None
        if random.random() < 0.1:  # 10% chance of null value in travel date
            travel_date = None
        if random.random() < 0.1:  # 10% chance of corrupt airline name
            airline = airline[:random.randint(1, len(airline)-1)]  # Corrupt airline name by trimming it
        if random.random() < 0.05:  # 5% chance of negative price
            price = -random.randint(3000, 15000)
        else:
            price = random.randint(3000, 15000)

        # Randomly change the date format for booking and travel dates
        if random.random() < 0.05:  # 5% chance of incorrect date format
            booking_date = booking_date.strftime("%d/%m/%Y") if booking_date else None
        if random.random() < 0.05:  # 5% chance of incorrect travel date format
            travel_date = travel_date.strftime("%d/%m/%Y") if travel_date else None

        flight_booking_data.append({
            "Booking_ID": len(flight_booking_data) + 1,  # Unique Booking ID
            "Booking_Date": booking_date,
            "Airline": airline,
            "Travel_Date": departure_time.strftime("%Y-%m-%d %H:%M:%S") if travel_date else None,
            "Arrival_Date": arrival_time.strftime("%Y-%m-%d %H:%M:%S") if travel_date else None,
            "Source": source,
            "Destination": destination,
            "Price": price,
            "Passenger_ID": passenger_id  # Foreign key reference to Passenger_ID
        })

# Limit flight bookings to 500 records
flight_booking_data = flight_booking_data[:500]

# Create DataFrames for passengers and flight bookings
passenger_df = pd.DataFrame(passenger_data)
flight_booking_df = pd.DataFrame(flight_booking_data)

In [7]:
passenger_df.head(3)

   Passenger_ID Passenger_Name            Class
0             1     Odika Rama  Premium Economy
1             2       Ryan Jha         Business
2             3     Megha Keer          Economy

In [9]:
flight_booking_df.head(50)

,Booking_ID,Booking_Date,Airline,Travel_Date,Arrival_Date,Source,Destination,Price,Passenger_ID
0,1,2021-01-09 00:00:00,SpiceJet,2021-01-29 14:49:00,2021-01-29 19:47:00,Pune,Delhi,7996,1
1,2,2021-04-27 00:00:00,Akasa Air,2021-04-28 09:08:00,2021-04-28 13:16:00,Lucknow,Delhi,9011,1
2,3,2022-10-18 00:00:00,Akasa Air,2022-11-16 11:19:00,2022-11-16 14:16:00,Hyderabad,Patna,10179,1
3,4,2020-12-07 00:00:00,TruJet,2020-12-14 19:19:00,2020-12-15 01:54:00,Delhi,Chennai,7452,2
4,5,2021-04-02 00:00:00,SpiceJet,2021-04-26 21:44:00,2021-04-27 03:21:00,Patna,Indore,9741,2
5,6,2020-01-26 00:00:00,Akasa Air,2020-02-18 15:32:00,2020-02-18 21:02:00,Ahmedabad,Jaipur,6563,2
6,7,31/12/2018,Vistara,2019-01-12 06:19:00,2019-01-12 11:25:00,Hyderabad,Bangalore,5310,3
7,8,2022-12-09 00:00:00,Alliance Air,2022-12-27 05:43:00,2022-12-27 13:03:00,Ahmedabad,Bangalore,12992,3
8,9,2018-06-25 00:00:00,TruJet,2018-07-10 18:29:00,2018-07-11 02:04:00,Hyderabad,Bangalore,9156,3
9,10,2019-07-17 00:00:00,IndiGo,2019-07-29 15:53:00,2019-07-29 16:55:00,Kolkata,Chennai,3975,4
10,11,2020-05-14 00:00:00,Alliance Air,2020-05-16 12:56:00,2020-05-16 17:51:00,Lucknow,Patna,13734,4
11,12,2020-12-03 00:00:00,Akasa Air,2020-12-17 13:41:00,2020-12-17 18:57:00,Ahmedabad,Chennai,12501,5
12,13,2018-02-25 00:00:00,IndiGo,2018-02-27 05:39:00,2018-02-27 10:45:00,Jaipur,Chennai,4044,5
13,14,2022-05-29 00:00:00,TruJet,2022-06-16 17:34:00,2022-06-16 21:34:00,Chennai,Bangalore,11712,6
14,15,2022-03-21 00:00:00,Akasa Air,2022-03-29 14:42:00,2022-03-29 16:52:00,Ahmedabad,Mumbai,6726,6
15,16,2019-10-16 00:00:00,Akasa Air,None,None,Hyderabad,Bangalore,-7689,6
16,17,2019-12-30 00:00:00,Alliance Air,2020-01-24 11:25:00,2020-01-24 19:08:00,Kolkata,Jaipur,4174,7
17,18,2018-04-30 00:00:00,Star Air,2018-05-25 16:04:00,2018-05-25 22:10:00,Mumbai,Bangalore,3731,8
18,19,2020-10-11 00:00:00,Star Air,2020-10-26 21:53:00,2020-10-27 04:49:00,Jaipur,Mumbai,3531,8
19,20,2019-11-14 00:00:00,Air India,2019-12-09 09:28:00,2019-12-09 11:12:00,Goa,Jaipur,10632,9
20,21,2018-07-26 00:00:00,Akasa Air,2018-08-08 19:02:00,2018-08-09 00:39:00,Hyderabad,Chennai,11588,9
21,22,2021-12-12 00:00:00,AirAsia India,2021-12-23 13:02:00,2021-12-23 19:49:00,Goa,Kolkata,12882,9
22,23,2018-02-16 00:00:00,SpiceJet,2018-03-16 12:26:00,2018-03-16 19:33:00,Mumbai,Cochin,3585,10
23,24,2022-03-25 00:00:00,TruJet,2022-03-30 17:01:00,2022-03-30 21:29:00,Ahmedabad,Hyderabad,13666,10
24,25,2018-10-22 00:00:00,SpiceJet,None,None,Pune,Hyderabad,-7842,11
25,26,None,Air India,2020-01-02 20:25:00,2020-01-03 02:17:00,Hyderabad,Bangalore,7247,12
26,27,None,Go First,2022-12-03 17:19:00,2022-12-04 01:00:00,Bangalore,Pune,-8692,13
27,28,2018-05-20 00:00:00,Al,2018-05-31 19:25:00,2018-06-01 01:17:00,Hyderabad,Patna,14605,14
28,29,2021-08-19 00:00:00,Star Air,2021-09-17 18:04:00,2021-09-17 23:41:00,Bangalore,Kolkata,7547,14
29,30,None,Star Air,2019-01-20 15:25:00,2019-01-20 18:16:00,Kolkata,Jaipur,10004,15
30,31,None,Vistara,2022-09-07 16:51:00,2022-09-07 20:09:00,Goa,Jaipur,14980,16
31,32,2021-08-23 00:00:00,Vistara,2021-08-29 21:55:00,2021-08-30 04:42:00,Delhi,Mumbai,8522,16
32,33,2020-03-04 00:00:00,Star Air,2020-03-20 11:53:00,2020-03-20 19:20:00,Cochin,Kolkata,13010,17
33,34,None,Go First,2021-06-11 11:19:00,2021-06-11 14:51:00,Cochin,Delhi,3693,18
34,35,22/08/2022,IndiGo,2022-08-27 20:36:00,2022-08-28 04:02:00,Cochin,Lucknow,4898,19
35,36,2020-01-18 00:00:00,AirAsia India,2020-01-23 20:28:00,2020-01-24 02:18:00,Pune,Delhi,12502,20
36,37,2022-10-30 00:00:00,Go First,2022-11-18 16:11:00,2022-11-18 22:55:00,Pune,Lucknow,4556,21
37,38,2020-05-10 00:00:00,Air India,2020-05-18 07:10:00,2020-05-18 09:30:00,Indore,Kolkata,5689,21
38,39,2018-10-04 00:00:00,Air India,2018-10-09 06:17:00,2018-10-09 08:44:00,Kolkata,Bangalore,3286,22
39,40,2018-01-18 00:00:00,Akasa Air,2018-01-27 20:10:00,2018-01-28 00:14:00,Bangalore,Ahmedabad,7269,22
40,41,2018-02-11 00:00:00,IndiGo,2018-03-08 21:09:00,2018-03-09 03:32:00,Bangalore,Ahmedabad,8004,23
41,42,2018-02-08 00:00:00,Air India,2018-02-20 16:31:00,2018-02-20 20:56:00,Bangalore,Hyderabad,10233,23
42,43,2020-08-29 00:00:00,Alliance Air,2020-09-13 05:53:00,2020-09-13 12:29:00,Patna,Goa,12113,24
43,44,2020-10-12 00:00:00,Go First,2020-10-31 20:39:00,2020-11-01 00:40:00,Ahmedabad,Bangalore,13249,24
44,45,2020-04-27 00:00:00,Alliance Air,None,None,Mumbai,Kolkata,4080,25
45,46,2019-11-13 00:00:00,AirAsia India,2019-11-25 08:43:00,2019-11-25 14:57:00,Cochin,Chennai,4424,25
46,47,2018-08-21 00:00:00,Go First,2018-09-19 07:08:00,2018-09-19 10:30:00,Hyderabad,Cochin,12166,25
47,48,28/04/2020,AirAsia India,2020-05-07 07:02:00,2020-05-07 08:37:00,Pune,Cochin,3141,26
48,49,2021-05-05 00:00:00,Star Air,None,None,Jaipur,Kolkata,3083,27
49,50,2022-06-24 00:00:00,SpiceJet,2022-07-07 12:51:00,2022-07-07 15:29:00,Cochin,Kolkata,3216,27

In [10]:
# Optionally save to CSV files
passenger_df.to_csv("passengers_dirty.csv", index=False)
flight_booking_df.to_csv("flight_bookings_dirty.csv", index=False)